name: appupdate_example
description: "Demonstrates how to use the appupdate plugin."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  play_in_app_update:
    path: ../

  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
